name: CI workflow

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  run-docker:
    name: Deploy the FE application on S3
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Cache Node.js modules
        uses: actions/cache@v3
        with:
          path: ~/.npm # Cache npm modules
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }} # Unique key based on package-lock.json
          restore-keys: |
            ${{ runner.os }}-npm-

      - name: Install dependencies
        run: |
          npm install --legacy-peer-deps
          npm run build  # If you're using a static site generator like Vite, Jekyll, or Gatsby
        env:
          VITE_BE_BASE_URL: ${{ secrets.VITE_BE_BASE_URL }}

      - name: Deploy
        run: echo "Running deployment on branch ${{ github.ref }}"

      - name: Configure AWS credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_ROLE }}
          aws-region: ap-southeast-1

      - name: Sync files to S3
        run: |
          aws s3 sync ./build s3://${{ secrets.S3_BUCKET_NAME }} --delete
        env:
          S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
