name: CI workflow

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  run-docker:
    name: Builds Docker Image
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - name: Checkouts Code
        uses: actions/checkout@v2

      - name: Caches Node.js modules
        uses: actions/cache@v3
        with:
          path: ~/.npm # Cache npm modules
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }} # Unique key based on package-lock.json
          restore-keys: |
            ${{ runner.os }}-npm-

      - name: Logins to docker registry
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}

      - name: Builds and pushes docker image to registry
        uses: docker/build-push-action@v5
        with:
          context: ./
          push: true
          tags: jukibach/nozma-fe:latest
