name: CI workflow

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  run-docker:
    name: Deploy the FE application on S3
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Cache Node.js modules
        uses: actions/cache@v3
        with:
          path: ~/.npm # Cache npm modules
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }} # Unique key based on package-lock.json
          restore-keys: |
            ${{ runner.os }}-npm-

      - name: Install dependencies
        run: |
          npm install --legacy-peer-deps
          npm run build  # If you're using a static site generator like Vite, Jekyll, or Gatsby
        env:
          VITE_BE_BASE_URL: ${{ secrets.VITE_BE_BASE_URL }}
